/* TODO: Replace w/ Actual TOS (via intl) once provided */
export const MOCK_TOS = `
Lorem ipsum dolor sit amet consectetur adipisicing elit. In molestiae recusandae accusantium quidem illo laudantium cum delectus deserunt error iure temporibus pariatur soluta ducimus sit, sunt aspernatur repudiandae culpa ipsum!
Quia cum earum exercitationem illo tempora reprehenderit nulla consequuntur, dolores ipsa natus aliquid quis id magnam iure aut ducimus, beatae a harum at. Labore perspiciatis accusamus repellendus, laborum explicabo magni?
Dicta, corporis hic ab cupiditate, obcaecati eum, quo omnis magnam tenetur reprehenderit fugit minus quia officiis. Dolorem in nesciunt velit provident officiis commodi neque error, saepe illo porro iure atque.
Assumenda nostrum facilis sed alias blanditiis officia eaque, earum ipsum, libero tempora accusantium saepe facere? Harum ratione saepe ab sit officia aliquid, itaque aliquam quam cumque illo suscipit sed ullam?
Quis officia voluptates nisi veritatis similique nesciunt iusto aspernatur quisquam ratione, quia dolor fugit blanditiis voluptatibus exercitationem maxime alias molestias placeat eum reprehenderit voluptatem delectus. Quasi quaerat iusto voluptas quae!
Natus unde sit consectetur id eum. Repellat, voluptate cum? Earum sit, officia ad enim placeat incidunt praesentium ipsum voluptatum, exercitationem delectus perferendis, ipsa dolor natus obcaecati eius corrupti nemo similique?
Corrupti ut doloribus rerum obcaecati veniam dolores ratione magnam, adipisci iusto atque cumque tempora earum nobis sunt iure cupiditate excepturi consequatur similique maiores debitis quisquam dolorum, nihil commodi? Cupiditate, maiores?
Esse soluta error aliquid culpa impedit! Nesciunt blanditiis repudiandae maiores maxime soluta perferendis ab vitae asperiores deleniti, ipsum vel porro iusto accusantium doloribus, officiis autem quia beatae! Modi, fugit eaque!
Quo tenetur quia nobis nesciunt rerum facilis, labore repellendus sed impedit delectus ratione ipsa, doloremque dolorem quos maxime explicabo est quidem dolore animi laborum perferendis aliquid repellat nihil! Modi, quasi.
Corporis fuga quibusdam tempore cumque, eveniet, laboriosam, id tempora nostrum dolor exercitationem iure totam a unde soluta modi qui nobis eum iusto voluptatum sint doloremque impedit? Cupiditate tenetur qui voluptatem.
Deleniti dolorum eaque voluptate accusantium sunt rerum. Quibusdam ipsam corporis dolores praesentium quis a explicabo, saepe magnam deleniti beatae aut ducimus. Ea itaque porro molestiae magni placeat officiis expedita alias?
Assumenda, porro. Nulla ea sunt obcaecati. Voluptates tenetur in assumenda temporibus unde rem explicabo necessitatibus nihil. Voluptatum temporibus eligendi eum illo sint laudantium. Nam esse, eveniet maiores earum modi consequuntur?
Ab dolores, odit ut numquam, repellendus quas ratione porro culpa voluptas, facilis temporibus suscipit. Veniam atque dignissimos explicabo distinctio non nemo id eveniet, quod, eos laboriosam obcaecati suscipit eum dolorum.
Distinctio ipsum voluptatem quos asperiores quis, qui maiores beatae quia cumque numquam laboriosam nostrum mollitia voluptates culpa laudantium sequi quisquam dolore laborum maxime, deleniti ratione blanditiis! Perspiciatis fugit porro placeat?
Nesciunt quisquam culpa vero odit, saepe rem corporis labore pariatur alias voluptates veniam maxime ducimus, incidunt impedit repellendus numquam fuga nemo commodi nisi a obcaecati deserunt porro? Quibusdam, doloribus magni.
Quos, unde. Alias unde molestias hic magnam sunt nam possimus saepe sapiente incidunt id corporis, ipsam libero aspernatur asperiores animi voluptates, assumenda dolor consequatur velit eveniet. Maiores veritatis sit unde!
Deleniti, quasi. Non cupiditate possimus enim, eum veritatis fugit rem harum. Reiciendis commodi maxime quidem corporis consequatur error nihil magnam, itaque similique. Neque earum recusandae in, incidunt vero odio voluptates.
Saepe nostrum delectus ab veniam numquam quod iure harum facere error, excepturi quaerat praesentium. Magni vitae placeat eius natus excepturi sit libero iste cupiditate qui, non similique hic voluptatem perspiciatis?
In, inventore. Voluptatibus quas laborum totam dolor aliquam! In molestiae sapiente quidem! Vero quis fuga corporis, maiores repellat et voluptate repellendus fugiat sapiente, perferendis laborum repudiandae reprehenderit expedita commodi unde?
Tenetur sed voluptatem fugiat atque repellat rerum aspernatur eius. Vel eaque eum ab corrupti natus repellat, ex nam reprehenderit voluptatum placeat fugit veniam optio molestias rem quasi aut. Ipsam, eum!
`;