image: node:14.19.0
options:
  max-time: 20
pipelines:
  custom:
    standard:
        - step: &install
            name: Get Dependencies
            caches:
            - node
            script:
            - yarn install --frozen-lockfile
            artifacts:
            - node_modules/**
            - public/**
        - parallel: &tests
            - step:
                name: Lint
                script:
                - npm run lint
            - step:
                name: Unit Test
                script:
                - npm run test:unit
            - step:
                name: E2E Test
                script:
                - chmod 755 ./ci/misc/web-e2e.sh
                - ./ci/misc/web-e2e.sh
            - step:
                name: Build
                script:
                - apt-get update
                - apt install -y wine
                - dpkg --add-architecture i386
                - npm run build
                - npm run build-pack:electron
  default:
    - step: *install
    - parallel: *tests
  branches:
    master:
      - step: *install
      - parallel: *tests
