export default {
  SET_ALL_ADDRESSES: 'TRANSACTIONS/SET_ALL_ADDRESSES',
  SET_TRANSACTIONS: 'TRANSACTIONS/SET_TRANSACTIONS',
  SET_TRANSACTIONS_SEARCH_RESULTS: 'TRANSACTIONS/SET_TRANSACTIONS_SEARCH_RESULTS',
};