export default {
  SET_SELECTED_WALLET: 'WALLETS/SET_SELECTED_WALLET',
  SET_SELECTED_WALLET_ADDRESSES: 'WALLETS/SET_SELECTED_WALLET_ADDRESSES',
  SET_SELECTED_WALLET_TRANSACTIONS: 'WALLETS/SET_SELECTED_WALLET_TRANSACTIONS',
  SET_SELECTED_TRANSACTIONS_SEARCH_RESULTS: 'WALLETS/SET_SELECTED_TRANSACTIONS_SEARCH_RESULTS',
  CLEAR_SELECTED_WALLET_TRANSACTIONS: 'WALLETS/CLEAR_SELECTED_WALLET_TRANSACTIONS',
  SET_WALLETS: 'WALLETS/SET_WALLETS',
  CLEAR: 'WALLETS/CLEAR_WALLET_DATA',
};