const GRID_COLUMNS = {
  FIRST_COLUMN: '1/3',
  SECOND_COLUMN: '4/7',
  THIRD_COLUMN: '7/10',
  FOURTH_COLUMN: '11/12',
};

const PLACEHOLDER_USD_VALUE = '$5,911.19';

export { GRID_COLUMNS, PLACEHOLDER_USD_VALUE };