name: Automerge
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: yarn install
      - run: yarn run lint
      - run: yarn run build --if-present
      - run: yarn run build:mobile
      - run: yarn run test:unit
      - run: chmod 755 ./ci/misc/web-e2e.sh
      - run: ./ci/misc/web-e2e.sh

  automerge:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: "Merge"
        uses: "nucleos/auto-merge-action@1.0.0"
        env:
          "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
