export default {
  RESET_FIELDS: 'SEND_FUNDS/RESET_FIELDS',
  SET_AMOUNT: 'SEND_FUNDS/SET_AMOUNT',
  SET_FROM_ADDRESS: 'SEND_FUNDS/SET_FROM_ADDRESS',
  SET_MEMO: 'SEND_FUNDS/SET_MEMO',
  SET_TO_ADDRESS: 'SEND_FUNDS/SET_TO_ADDRESS',
};