export default {
  PRE_SELECT_FROM_ADDRESS: 'SEND_FUNDS/PRE_SELECT_FROM_ADDRESS',
  PRE_SELECT_TO_ADDRESS: 'SEND_FUNDS/PRE_SELECT_TO_ADDRESS',
  RESET_FIELDS: 'SEND_FUNDS/RESET_FIELDS',
  SET_AMOUNT: 'SEND_FUNDS/SET_AMOUNT',
  SET_FEE: 'SEND_FUNDS/SET_FEE',
  SET_FROM_ADDRESS: 'SEND_FUNDS/SET_FROM_ADDRESS',
  SET_MEMO: 'SEND_FUNDS/SET_MEMO',
  SET_TO_ADDRESS: 'SEND_FUNDS/SET_TO_ADDRESS',
};